public class difference {
    /**  time complexity - O(N)
     space complexity -O(1)
     You are given two strings s and t.

     String t is generated by random shuffling string s and then add one more letter at a random position.

     Return the letter that was added to t.



     Example 1:

     Input: s = "abcd", t = "abcde"
     Output: "e"
     Explanation: 'e' is the letter that was added.
     Example 2:

     Input: s = "", t = "y"
     Output: "y"
     */
    public char findTheDifference(String s, String t) {
        int originalCount =0;
        int newCount=0;
        for(int i=0;i<s.length();i++){
            originalCount +=(int)s.charAt(i);
        }
        for(int j=0;j<t.length();j++){
            newCount +=(int)t.charAt(j);
        }
        return (char)(newCount-originalCount);
    }
}
